services:
  # Container definition for the devcontainer
  devcontainer:
    build:
      context: .
      args:
        PYTHON_VERSION: ${PYTHON_VERSION:-3.14.3}
      target: dev
    stdin_open: true
    tty: true
    volumes:
      - .:/workspaces/marty_mcfly/

  # Container definition for running the production app image
  app:
    build:
      context: .
      target: app
    tty: true
    ports:
      - "8001:8000"
    volumes:
      - .:/workspaces/marty_mcfly/
    command: ["serve", "--dev"]

networks:
  default:
    name: marty_mcfly-network
